export type Accept =
	| "pdf"
	| "image"
	| "image/jpeg"
	| "image/png"
	| "image/gif"
	| "image/webp"
	| "image/svg+xml"
	| "document"
	| "application/msword"
	| "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	| "application/vnd.ms-excel"
	| "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	| "application/vnd.ms-powerpoint"
	| "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	| "text/plain"
	| "text/csv"
	| "archive"
	| "application/zip"
	| "application/x-rar-compressed"
	| "application/x-7z-compressed"
	| ({} & string);
